import { GoogleAnalytics } from '@next/third-parties/google'
import { Press_Start_2P, Creepster } from 'next/font/google'
import './globals.css'

const pixelFont = Press_Start_2P({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-pixel',
})

const creepyFont = Creepster({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-creepy',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${creepyFont.variable} ${pixelFont.variable} antialiased font-body h-full bg-neutral-900 relative`}
			>
				{children}
			</body>
			<GoogleAnalytics gaId="G-WR031DMPZQ" />
		</html>
	)
}
